---
#deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-app
  namespace: default
  labels:
    app: springboot-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: springboot-app
  template:
    metadata:
      labels:
        app: springboot-app
    spec:
      containers:
        - name: springboot-container
          image: ghcr.io/howtodie123/backend:main-50b523d16e74a10b022706442ab774cfcf0d0ac6
          imagePullPolicy: Always
          env:
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                secretKeyRef:
                  name: springboot-se
                  key: spring.datasource.url
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: springboot-se
                  key: spring.datasource.username
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: springboot-se
                  key: spring.datasource.password
            - name: SPRING_MAIL_USERNAME
              valueFrom:
                secretKeyRef:
                  name: springboot-se
                  key: spring.mail.username
            - name: SPRING_MAIL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: springboot-se
                  key: spring.mail.password
          ports:
            - containerPort: 8080
          resources:  
            requests:
              cpu: "250m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"

---
# Service
apiVersion: v1
kind: Service
metadata:
  name: springboot-service
  namespace: default
spec:
  selector:
    app: springboot-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: LoadBalancer