apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: gcp-secret-store
  namespace: external-secrets
spec:
  provider:
    gcpsm:
      auth:
        workloadIdentity:
         clusterLocation: asia-southeast1  
         clusterName: demo-cluster1    
         serviceAccountRef:
            name: external-secrets
            namespace: external-secrets
      projectID: unified-smoke-451902-i4  

