global:
  scrape_interval: 10s  # Lấy dữ liệu mỗi 10 giây
  evaluation_interval: 10s  # Đánh giá rules mỗi 10 giây

scrape_configs:

  - job_name: 'spring-boot-app'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['app:8080']

  - job_name: 'postgresql'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['postgres-exporter:9187']

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']