name: CI/CD workflow for Maven Build and Sonar Code scan
on:
  push:
    branches:
      - main
  workflow_dispatch:
  pull_request:

jobs:
  unit-tests:
    name: Unit tests
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: Backend
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-m2

      - name: Run Unit Tests
        run: chmod +x mvnw
        run: ./mvnw test

  integration-tests:
    name: Integration Test
    runs-on: ubuntu-latest
    needs: unit-tests  
    defaults:
      run:
        shell: bash
        working-directory: Backend
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1  

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-m2

      - name: Resolve dependencies
        run: chmod +x mvnw
        run: ./mvnw dependency:resolve-plugins dependency:resolve

      - name: Run integration tests
        run: ./mvnw verify -DskipUnitTests
